### ISSUE TITLE
Sonarqube decorator:Pr job is not triggered if send 2 pushes in pull request

### ISSUE THREAD

**Issue by okamara** [zebrunner/pipeline-ce#65]

**Comment by sandinosanchez** [comment]
Delivered in #69 

**Environment**

   - Zebrunner-ce > develop branch

**Objective**

   - Verify that the webhook triggering for pr/mr is actually triggered by pushing to the source branch instead of opening/reopening pr/mr.

**Pre-conditions**

   - carina-demo forked into your gitlab and github account.

**Test steps**

   1. Run registerOrganization
   2. Run register Repository with carina-demo
   3. Configure webhooks for your repositries. Follow steps **Setup webhook events** and **Sonarqube integration** on this [guide](https://zebrunner.github.io/zebrunner/config-guide/#setup-webhook-events-push-and-pull-requests) to configure them
   4. Go to your repo, create a branch from master and
      - Copy [this](https://github.com/sandinosanchez/carina-demo/blob/pr-test14/src/main/java/com/qaprosoft/carina/demo/gui/pages/HomePage.java#L39) line of code at the same location in your branch(**src/main/java/com/qaprosoft/carina/demo/gui/pages/HomePage.java**).
      - Copy [this](https://github.com/sandinosanchez/carina-demo/blob/faa200b0e80609f2995ddd3c9c3cf8747819bc87/src/main/java/com/qaprosoft/carina/demo/gui/pages/HomePage.java#L50) from line 50 to 52 and paste it in the same location in your branch(**src/main/java/com/qaprosoft/carina/demo/gui/pages/HomePage.java**)
   5. Open your source pr/mr branch and modify something on the **README.MD**

**Special anotation:**

   - Run the test case for carina-demo on gitlab and github.

**Expected results**

   4. onPullRequest job for your target repository triggered and executed successfully from pr/mr **creation** and the sonar analysis report is decorated into the pr/mr.
   5. onPullRequest job for your target repository triggered and executed successfully from pr/mr **update**.

**Comment by okamara** [comment]
Gitlab is fixed. Github will be reverified after fix https://github.com/zebrunner/pipeline-ce/issues/70
